; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware/src
lib_dir = firmware/lib

[env]
platform = espressif32 @ 6.12.0
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17
extra_scripts = pre:scripts/env_config.py
board_build.partitions = firmware/partition.csv
check_tool = clangtidy
check_flags =
    clangtidy: --config-file=.clang-tidy
check_skip_packages = yes
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
    ESP32Async/AsyncTCP @ 3.4.10
    ESP32Async/ESPAsyncWebServer @ 3.9.6

[env:Debug]
upload_speed = 115200
monitor_speed = 115200

[env:OTA]
upload_protocol = custom
upload_command = bash -c 'HASH=$$(md5sum "$SOURCE" | cut -d" " -f1) && curl -fsSL -F "file=@$SOURCE" "http://$UPLOAD_PORT/api/firmware/update?hash=$$HASH"'
