// Reads frontend build output, gzips each file, and generates a C header
// with PROGMEM byte arrays for embedding in firmware.
//
// Usage: node frontend/scripts/embed_frontend.js

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const distDir = path.join(__dirname, "..", "dist");
const outHeader = path.join(__dirname, "..", "..", "firmware", "src", "web_assets.h");

const files = [
    { src: "index.html", varName: "INDEX_HTML", contentType: "text/html" },
    { src: "app.js", varName: "APP_JS", contentType: "application/javascript" },
];

function toHexArray(buffer) {
    const bytes = [];
    for (let i = 0; i < buffer.length; i++) {
        bytes.push("0x" + buffer[i].toString(16).padStart(2, "0"));
    }
    // 12 bytes per line
    const lines = [];
    for (let i = 0; i < bytes.length; i += 12) {
        lines.push("    " + bytes.slice(i, i + 12).join(", "));
    }
    return lines.join(",\n");
}

let header = `#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <Arduino.h>

// Auto-generated by scripts/embed_frontend.js — do not edit
`;

for (const file of files) {
    const filePath = path.join(distDir, file.src);
    if (!fs.existsSync(filePath)) {
        console.error(`Missing: ${filePath}`);
        process.exit(1);
    }

    const raw = fs.readFileSync(filePath);
    const gzipped = zlib.gzipSync(raw, { level: 9 });

    console.log(
        `${file.src}: ${raw.length} bytes -> ${gzipped.length} bytes gzipped`
    );

    header += `
// ${file.src} (${raw.length} bytes raw, ${gzipped.length} bytes gzipped)
const char ${file.varName}_CONTENT_TYPE[] PROGMEM = "${file.contentType}";
const uint8_t ${file.varName}_GZ[] PROGMEM = {
${toHexArray(gzipped)}
};
const size_t ${file.varName}_GZ_LEN = ${gzipped.length};
`;
}

header += `
#endif // WEB_ASSETS_H
`;

fs.writeFileSync(outHeader, header);
console.log(`Generated: ${outHeader}`);
