// Reads frontend build output, gzips each file, and generates a C header
// with PROGMEM byte arrays for embedding in firmware.
//
// Auto-discovers all files in dist/ so new assets (CSS, JS chunks, fonts, etc.)
// are embedded without editing this script or the web server.
//
// Usage: node frontend/scripts/embed_frontend.js

const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");

const distDir = path.join(__dirname, "..", "dist");
const outHeader = path.join(__dirname, "..", "..", "firmware", "src", "web_assets.h");

// MIME type lookup by extension (keep minimal, expand as needed)
const mimeTypes = {
    ".html": "text/html",
    ".js": "application/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
};

function getContentType(filePath) {
    const ext = path.extname(filePath).toLowerCase();
    return mimeTypes[ext] || "application/octet-stream";
}

// Recursively collect all files under a directory
function collectFiles(dir, base) {
    const results = [];
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name);
        const relPath = path.join(base, entry.name);
        if (entry.isDirectory()) {
            results.push(...collectFiles(fullPath, relPath));
        } else if (entry.isFile()) {
            results.push(relPath);
        }
    }
    return results;
}

// Convert a relative file path to a valid C identifier (UPPER_SNAKE_CASE)
function toVarName(relPath) {
    return relPath
        .replace(/^\/+/, "")
        .replace(/[^a-zA-Z0-9]/g, "_")
        .toUpperCase();
}

function toHexArray(buffer) {
    const bytes = [];
    for (let i = 0; i < buffer.length; i++) {
        bytes.push(`0x${buffer[i].toString(16).padStart(2, "0")}`);
    }
    const lines = [];
    for (let i = 0; i < bytes.length; i += 12) {
        lines.push(`    ${bytes.slice(i, i + 12).join(", ")}`);
    }
    return lines.join(",\n");
}

if (!fs.existsSync(distDir)) {
    console.error(`Missing dist directory: ${distDir}`);
    process.exit(1);
}

const relPaths = collectFiles(distDir, "").sort();
if (relPaths.length === 0) {
    console.error("No files found in dist/");
    process.exit(1);
}

let header = `#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <Arduino.h>

// Auto-generated by scripts/embed_frontend.js — do not edit
// Assets are discovered automatically from the frontend dist/ directory.

struct WebAsset {
    const char *path;        // URL path (e.g. "/index.html", "/app.js")
    const char *contentType; // MIME type
    const uint8_t *data;     // Gzipped content
    size_t length;           // Gzipped content length
};

`;

const assetEntries = [];

for (const relPath of relPaths) {
    const filePath = path.join(distDir, relPath);
    const raw = fs.readFileSync(filePath);
    const gzipped = zlib.gzipSync(raw, { level: 9 });
    const contentType = getContentType(relPath);
    const varName = toVarName(relPath);
    // URL path: always forward-slash, rooted
    const urlPath = `/${relPath.split(path.sep).join("/")}`;

    console.log(`${urlPath}: ${raw.length} bytes -> ${gzipped.length} bytes gzipped (${contentType})`);

    header += `// ${urlPath} (${raw.length} bytes raw, ${gzipped.length} bytes gzipped)
static const char ${varName}_PATH[] PROGMEM = "${urlPath}";
static const char ${varName}_CT[] PROGMEM = "${contentType}";
static const uint8_t ${varName}_GZ[] PROGMEM = {
${toHexArray(gzipped)}
};
static const size_t ${varName}_GZ_LEN = ${gzipped.length};

`;

    assetEntries.push(`    {${varName}_PATH, ${varName}_CT, ${varName}_GZ, ${varName}_GZ_LEN}`);

    // Register "/" as an alias for "/index.html" so the SPA root works
    if (urlPath === "/index.html") {
        assetEntries.push(`    {"/" , ${varName}_CT, ${varName}_GZ, ${varName}_GZ_LEN}`);
    }
}

header += `// Asset registry — iterable by the web server
static const WebAsset WEB_ASSETS[] PROGMEM = {
${assetEntries.join(",\n")}
};
static const size_t WEB_ASSETS_COUNT = ${assetEntries.length};

#endif // WEB_ASSETS_H
`;

fs.writeFileSync(outHeader, header);
console.log(`Generated: ${outHeader} (${assetEntries.length} assets)`);
